sensiolabs/SensioDistributionBundle

- Resources/bin/build_bootstrap.php
| Q             | A
| ------------- | ---
| License       | MIT
Allows ./build_bootstrap.php 0 0 1 to use new directory structure without manually specifiying bootstrap & autoload dir
You currently can’t set $useNewDirectoryStructure to true (third argument) without specifiying the first & second argument.
> Fix unreachable condition in build_bootstrap.php

- Composer/ScriptHandler.php
FileSystem->mirror function documentation explains this :
Valid options are:
*                                 - $options['override'] Whether to override an existing file on copy or not (see copy())
> Fix override option on acme-bundle creation

- Composer/ScriptHandler.php
So far handles Heroku.
Uses `$STACK` to detect cedar/cedar-14 builds and writes a `Procfile` with the boot command for the correct document root if no `Procfile` exists.
Needs `Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap` in `post-install-cmd`.
cc @fabpot
> prepareDeploymentTarget script handler

- Composer/ScriptHandler.php
In Symfony 2.7, we should silence by default the deprecation notices that are triggered.
In debug, this is overwritten by Debug::enable() in app_dev.php
> Silence deprecation notices

- Composer/ScriptHandler.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #202
| License       | MIT
| Doc PR        | n/a
fixes #202
> [2.3] [bugfix] fixed new line at EOF while generating bootstrap.php.cache

- Composer/ScriptHandler.php
Hi there,
To facilitate a non-default directory structure with multiple kernels in our Symfony application, I've extended the ScriptHandler class to have the same Composer hooks as normal Symfony applications. To accomplish this, I have changed all `self::` calls with `static::` so the functions are overridable.
Cheers,
Robin
> Replaced self:: with static::

- composer.json
Given the webconfigurator has been removed from the bundle, most of the dependencies are not needed anymore.
> Clean the composer requirements

- Resources/skeleton/app/SymfonyRequirements.php
ext-iconv is already built by default into php since years (same as ext-json). Nobody has seen a php without iconv since years :) If we agree on this, then I could remove the iconv shim from https://github.com/symfony/symfony/pull/16240 and we could write code relying on `iconv*()` the same way we do for `json_encode`: without thinking about the function existence.
> Add iconv to requirements

- Composer/ScriptHandler.php
- Resources/bin/build_bootstrap.php
Continuation of https://github.com/symfony/symfony-standard/pull/854 to remove the obsolete mix of bootstrap and autoloading.
@fabpot it would be good to merge this in 5.0, even if you just created the first relase of it. 5.x is also the dependency in the standard edition now.
> remove autoloading from bootstrap file

- Resources/bin/build_bootstrap.php
In the current master and also in tags `~5.0.0` I get:
```php
$ ./vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php app/
Looks like you don't have a standard layout.
```
Because `build_bootstrap.php` is located in `/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php` and not in `/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php` as in `<=4.0`
> Fixed root path since moving to PSR-4 autoloading.

- UPGRADE.md
As I've not been very active in upgrade this package, I had to go from 3.0 to 5.0 and I encountered this issue. I tried to find out what was broken and got back to [this commit](https://github.com/sensiolabs/SensioDistributionBundle/commit/b6fd439d2afe45f8f73981e8bf9ff5d2891c0830). To save people some time, I've added the upgrade-5.0 file with this change documented.
I'm not sure if this change was introduced in 5.0.0 or a later patch version but it's a BC break nevertheless.
/cc @Tobion
> Added an upgrade file for 5.0

- Resources/skeleton/app/SymfonyRequirements.php
The `symfony_requirements` command checks if the php.ini setting `date.timezone` has been set and reports an error otherwise.
While this has been a good idea in php 5, this check is imho not necessary anymore when run on php 7, because php 7 is able to pick a reasonable default timezone without throwing a warning if the setting is missing.
Source: https://wiki.php.net/rfc/date.timezone_warning_removal
> Skip date.timezone check on php 7.0

- Composer/ScriptHandler.php
Without this fix, people upgrading to composer 1.1 when it's out (or snapshots right now) will get a lot of:
> Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile declared at vendor\sensio\distribution-bundle\Sensio\Bundle\DistributionBundle\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but symfony events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes
It's compatible with pretty old composer versions at this point so the change is harmless IMO.
> Update type hint to use the proper event class

- Controller/ConfiguratorController.php
I was looking for "catch all" statements and found this. IMHO the intention is not to ignore every possible error, including those in userland-implemented-routers (which could hide bugs), but to ignore the route, if it's not registered.
Btw, where did this class disappear in master?
> catch RouteNotFoundException instead of \Exception

- Resources/skeleton/app/SymfonyRequirements.php
People [get](https://github.com/symfony/symfony/issues/19453) [confused](https://github.com/symfony/symfony/issues/15007#issuecomment-234733703) by the current message added in #262. It only makes sense to be on the latest ICU data, as any other distribution is invalid (outdated). Therefore I suggest we keep the icu data up to date (https://github.com/symfony/symfony/pull/19468 was just merged), and raise a notice if the user is on an older version.
> Make the icu data version check less confusing

- Resources/skeleton/app/check.php
Hi,
When I run the command ``./bin/symfony_requirements``, I found that the size of the ERROR/OK blocks is too wide, and the extra line of each block is glued to the next title.
This PR will fix the background-colored block, as you can see on the screenshots.
What do you think about it?
> Fix the size of the background-colored block

- Composer/ScriptHandler.php
Closes https://github.com/sensiolabs/SensioDistributionBundle/issues/234.
In 2.7 or 2.8 using the old directory structure, the extra option "symfony-app-dir" in `composer.json` is already available and the `web/config.php`  should include the path accordingly as done [here](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L195).
> Fixed requirements link from config.php

- Composer/ScriptHandler.php
As spotted in https://github.com/symfony/symfony/issues/20753#issuecomment-264819158
`Kernel` inlining is not compatible with old `"files": ["app/AppKernel.php"]` entries in composer.json
> Dont inline Kernel when already there

- Composer/ScriptHandler.php
If app/autoload.php is absent then use the autoload.php in Composer's
vendor directory.
symfony/symfony#21837 opens the door for removing `app/autoload.php` in Symfony apps. I tried removing that and updating the various reference to it in symfony-standard and my app works (:tada:), but when I run composer install/update it complains about the buildBootstrap task expecting to find `app/autoload.php`.
This fix tells the buildBootstrap task to use `vendor/autoload.php` if `app/autoload.php` is absent.
> Allow building bootstrap.php.cache when app/autoload.php is absent

- Composer/ScriptHandler.php
See https://github.com/symfony/symfony/issues/22618
before
after
> Remove decoration from forwarded exception

- Resources/skeleton/app/SymfonyRequirements.php
Based on the issue of the timelib library, symfony can't use listAbbreviations method to check timezone, the recomendation is to use listIdentifiers method instead.
Related issues:
[https://github.com/derickr/timelib/issues/34](https://github.com/derickr/timelib/issues/34)
[https://github.com/sensiolabs/SensioDistributionBundle/issues/337](https://github.com/sensiolabs/SensioDistributionBundle/issues/337)
[https://github.com/symfony/symfony/issues/26550](https://github.com/symfony/symfony/issues/26550)
> Fix: Timezone Requirement

- composer.json
I'm not 100% sure if the 4.0 branch is still maintained, but this would ease the upgrading path to the new security checker.
This still allows the older versions to make sure there is no BC break if the system is incompatible with the new versions
Related to https://github.com/sensiolabs/security-checker/issues/133#issuecomment-444121362
> Allow wider range of security checker on version 4.*
